apiVersion: v1
kind: Secret
metadata:
  name: {{ include "morgenruf.fullname" . }}-secret
  labels:
    {{- include "morgenruf.labels" . | nindent 4 }}
type: Opaque
stringData:
  slack-bot-token: {{ .Values.secret.slackBotToken | quote }}
  slack-signing-secret: {{ .Values.secret.slackSigningSecret | quote }}
