apiVersion: v1
kind: Secret
metadata:
  name: {{ include "morgenruf.fullname" . }}-secret
  labels:
    {{- include "morgenruf.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation
type: Opaque
stringData:
  SLACK_CLIENT_ID: {{ .Values.slack.clientId | quote }}
  SLACK_CLIENT_SECRET: {{ .Values.slack.clientSecret | quote }}
  SLACK_SIGNING_SECRET: {{ .Values.slack.signingSecret | quote }}
  {{- if .Values.postgresql.enabled }}
  DATABASE_URL: {{ printf "postgresql://%s:%s@%s-postgresql:5432/%s" .Values.postgresql.auth.username .Values.postgresql.auth.password (include "morgenruf.fullname" .) .Values.postgresql.auth.database | quote }}
  {{- else }}
  DATABASE_URL: {{ .Values.externalDatabase.url | quote }}
  {{- end }}
  FLASK_SECRET_KEY: {{ .Values.flaskSecretKey | b64enc | quote }}
  RESEND_API_KEY: {{ .Values.resend.apiKey | quote }}
  APP_URL: {{ .Values.app.url | quote }}
  PORT: {{ .Values.app.port | quote }}
