apiVersion: v2
name: morgenruf
description: Self-hosted Slack standup bot with PostgreSQL
type: application
version: 0.10.3
appVersion: "1.7.3"
keywords:
  - slack
  - standup
  - bot
home: https://morgenruf.dev
sources:
  - https://github.com/morgenruf/morgenruf
maintainers:
  - name: morgenruf
    email: hello@morgenruf.dev
    url: https://morgenruf.dev
