apiVersion: v2
name: morgenruf
description: Self-hosted Slack app for async standups, coffee chats, kudos and insights
type: application
version: 0.11.2
appVersion: "1.8.2"
keywords:
  - slack
  - standup
  - coffee-chats
  - recognition
  - bot
home: https://morgenruf.dev
sources:
  - https://github.com/morgenruf/morgenruf
maintainers:
  - name: morgenruf
    email: hello@morgenruf.dev
    url: https://morgenruf.dev
