/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as AuthResultRouteImport } from './routes/auth.result'
import { Route as DashboardAuthenticatedRouteRouteImport } from './routes/dashboard/_authenticated/route'
import { Route as DashboardLoginRouteImport } from './routes/dashboard/login'
import { Route as EmailResultRouteImport } from './routes/email.result'
import { Route as FeedTokenRouteImport } from './routes/feed.$token'
import { Route as ConnectZoomResultRouteImport } from './routes/connect.zoom.result'
import { Route as DashboardAuthenticatedIndexRouteImport } from './routes/dashboard/_authenticated/index'
import { Route as DashboardAuthenticatedAnalyticsRouteImport } from './routes/dashboard/_authenticated/analytics'
import { Route as DashboardAuthenticatedAutomationRouteImport } from './routes/dashboard/_authenticated/automation'
import { Route as DashboardAuthenticatedConnectRouteRouteImport } from './routes/dashboard/_authenticated/connect/route'
import { Route as DashboardAuthenticatedInsightsRouteImport } from './routes/dashboard/_authenticated/insights'
import { Route as DashboardAuthenticatedKudosRouteImport } from './routes/dashboard/_authenticated/kudos'
import { Route as DashboardAuthenticatedMcpRouteImport } from './routes/dashboard/_authenticated/mcp'
import { Route as DashboardAuthenticatedMembersRouteImport } from './routes/dashboard/_authenticated/members'
import { Route as DashboardAuthenticatedReportsRouteImport } from './routes/dashboard/_authenticated/reports'
import { Route as DashboardAuthenticatedSettingsRouteImport } from './routes/dashboard/_authenticated/settings'
import { Route as DashboardAuthenticatedStandupsRouteImport } from './routes/dashboard/_authenticated/standups'
import { Route as DashboardAuthenticatedTodayRouteImport } from './routes/dashboard/_authenticated/today'
import { Route as DashboardAuthenticatedWebhooksRouteImport } from './routes/dashboard/_authenticated/webhooks'
import { Route as DashboardAuthenticatedConnectIndexRouteImport } from './routes/dashboard/_authenticated/connect/index'
import { Route as DashboardAuthenticatedConnectProgramIdRouteImport } from './routes/dashboard/_authenticated/connect/$programId'
import { Route as DashboardAuthenticatedConnectAttendanceRouteImport } from './routes/dashboard/_authenticated/connect/attendance'
import { Route as DashboardAuthenticatedConnectNewRouteImport } from './routes/dashboard/_authenticated/connect/new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResultRoute = AuthResultRouteImport.update({
  id: '/auth/result',
  path: '/auth/result',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAuthenticatedRouteRoute =
  DashboardAuthenticatedRouteRouteImport.update({
    id: '/_authenticated',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardLoginRoute = DashboardLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const EmailResultRoute = EmailResultRouteImport.update({
  id: '/email/result',
  path: '/email/result',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedTokenRoute = FeedTokenRouteImport.update({
  id: '/feed/$token',
  path: '/feed/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectZoomResultRoute = ConnectZoomResultRouteImport.update({
  id: '/connect/zoom/result',
  path: '/connect/zoom/result',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAuthenticatedIndexRoute =
  DashboardAuthenticatedIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardAuthenticatedRouteRoute,
  } as any)
const DashboardAuthenticatedAnalyticsRoute =
  DashboardAuthenticatedAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => DashboardAuthenticatedRouteRoute,
  } as any)
const DashboardAuthenticatedAutomationRoute =
  DashboardAuthenticatedAutomationRouteImport.update({
    id: '/automation',
    path: '/automation',
    getParentRoute: () => DashboardAuthenticatedRouteRoute,
  } as any)
const DashboardAuthenticatedConnectRouteRoute =
  DashboardAuthenticatedConnectRouteRouteImport.update({
    id: '/connect',
    path: '/connect',
    getParentRoute: () => DashboardAuthenticatedRouteRoute,
  } as any)
const DashboardAuthenticatedInsightsRoute =
  DashboardAuthenticatedInsightsRouteImport.update({
    id: '/insights',
    path: '/insights',
    getParentRoute: () => DashboardAuthenticatedRouteRoute,
  } as any)
const DashboardAuthenticatedKudosRoute =
  DashboardAuthenticatedKudosRouteImport.update({
    id: '/kudos',
    path: '/kudos',
    getParentRoute: () => DashboardAuthenticatedRouteRoute,
  } as any)
const DashboardAuthenticatedMcpRoute =
  DashboardAuthenticatedMcpRouteImport.update({
    id: '/mcp',
    path: '/mcp',
    getParentRoute: () => DashboardAuthenticatedRouteRoute,
  } as any)
const DashboardAuthenticatedMembersRoute =
  DashboardAuthenticatedMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => DashboardAuthenticatedRouteRoute,
  } as any)
const DashboardAuthenticatedReportsRoute =
  DashboardAuthenticatedReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => DashboardAuthenticatedRouteRoute,
  } as any)
const DashboardAuthenticatedSettingsRoute =
  DashboardAuthenticatedSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => DashboardAuthenticatedRouteRoute,
  } as any)
const DashboardAuthenticatedStandupsRoute =
  DashboardAuthenticatedStandupsRouteImport.update({
    id: '/standups',
    path: '/standups',
    getParentRoute: () => DashboardAuthenticatedRouteRoute,
  } as any)
const DashboardAuthenticatedTodayRoute =
  DashboardAuthenticatedTodayRouteImport.update({
    id: '/today',
    path: '/today',
    getParentRoute: () => DashboardAuthenticatedRouteRoute,
  } as any)
const DashboardAuthenticatedWebhooksRoute =
  DashboardAuthenticatedWebhooksRouteImport.update({
    id: '/webhooks',
    path: '/webhooks',
    getParentRoute: () => DashboardAuthenticatedRouteRoute,
  } as any)
const DashboardAuthenticatedConnectIndexRoute =
  DashboardAuthenticatedConnectIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardAuthenticatedConnectRouteRoute,
  } as any)
const DashboardAuthenticatedConnectProgramIdRoute =
  DashboardAuthenticatedConnectProgramIdRouteImport.update({
    id: '/$programId',
    path: '/$programId',
    getParentRoute: () => DashboardAuthenticatedConnectRouteRoute,
  } as any)
const DashboardAuthenticatedConnectAttendanceRoute =
  DashboardAuthenticatedConnectAttendanceRouteImport.update({
    id: '/attendance',
    path: '/attendance',
    getParentRoute: () => DashboardAuthenticatedConnectRouteRoute,
  } as any)
const DashboardAuthenticatedConnectNewRoute =
  DashboardAuthenticatedConnectNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => DashboardAuthenticatedConnectRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/auth/result': typeof AuthResultRoute
  '/dashboard/login': typeof DashboardLoginRoute
  '/email/result': typeof EmailResultRoute
  '/feed/$token': typeof FeedTokenRoute
  '/dashboard/connect': typeof DashboardAuthenticatedConnectRouteRouteWithChildren
  '/connect/zoom/result': typeof ConnectZoomResultRoute
  '/dashboard/analytics': typeof DashboardAuthenticatedAnalyticsRoute
  '/dashboard/automation': typeof DashboardAuthenticatedAutomationRoute
  '/dashboard/insights': typeof DashboardAuthenticatedInsightsRoute
  '/dashboard/kudos': typeof DashboardAuthenticatedKudosRoute
  '/dashboard/mcp': typeof DashboardAuthenticatedMcpRoute
  '/dashboard/members': typeof DashboardAuthenticatedMembersRoute
  '/dashboard/reports': typeof DashboardAuthenticatedReportsRoute
  '/dashboard/settings': typeof DashboardAuthenticatedSettingsRoute
  '/dashboard/standups': typeof DashboardAuthenticatedStandupsRoute
  '/dashboard/today': typeof DashboardAuthenticatedTodayRoute
  '/dashboard/webhooks': typeof DashboardAuthenticatedWebhooksRoute
  '/dashboard/': typeof DashboardAuthenticatedIndexRoute
  '/dashboard/connect/$programId': typeof DashboardAuthenticatedConnectProgramIdRoute
  '/dashboard/connect/attendance': typeof DashboardAuthenticatedConnectAttendanceRoute
  '/dashboard/connect/new': typeof DashboardAuthenticatedConnectNewRoute
  '/dashboard/connect/': typeof DashboardAuthenticatedConnectIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardAuthenticatedIndexRoute
  '/auth/result': typeof AuthResultRoute
  '/dashboard/login': typeof DashboardLoginRoute
  '/email/result': typeof EmailResultRoute
  '/feed/$token': typeof FeedTokenRoute
  '/connect/zoom/result': typeof ConnectZoomResultRoute
  '/dashboard/analytics': typeof DashboardAuthenticatedAnalyticsRoute
  '/dashboard/automation': typeof DashboardAuthenticatedAutomationRoute
  '/dashboard/insights': typeof DashboardAuthenticatedInsightsRoute
  '/dashboard/kudos': typeof DashboardAuthenticatedKudosRoute
  '/dashboard/mcp': typeof DashboardAuthenticatedMcpRoute
  '/dashboard/members': typeof DashboardAuthenticatedMembersRoute
  '/dashboard/reports': typeof DashboardAuthenticatedReportsRoute
  '/dashboard/settings': typeof DashboardAuthenticatedSettingsRoute
  '/dashboard/standups': typeof DashboardAuthenticatedStandupsRoute
  '/dashboard/today': typeof DashboardAuthenticatedTodayRoute
  '/dashboard/webhooks': typeof DashboardAuthenticatedWebhooksRoute
  '/dashboard/connect/$programId': typeof DashboardAuthenticatedConnectProgramIdRoute
  '/dashboard/connect/attendance': typeof DashboardAuthenticatedConnectAttendanceRoute
  '/dashboard/connect/new': typeof DashboardAuthenticatedConnectNewRoute
  '/dashboard/connect': typeof DashboardAuthenticatedConnectIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/_authenticated': typeof DashboardAuthenticatedRouteRouteWithChildren
  '/auth/result': typeof AuthResultRoute
  '/dashboard/login': typeof DashboardLoginRoute
  '/email/result': typeof EmailResultRoute
  '/feed/$token': typeof FeedTokenRoute
  '/dashboard/_authenticated/connect': typeof DashboardAuthenticatedConnectRouteRouteWithChildren
  '/connect/zoom/result': typeof ConnectZoomResultRoute
  '/dashboard/_authenticated/analytics': typeof DashboardAuthenticatedAnalyticsRoute
  '/dashboard/_authenticated/automation': typeof DashboardAuthenticatedAutomationRoute
  '/dashboard/_authenticated/insights': typeof DashboardAuthenticatedInsightsRoute
  '/dashboard/_authenticated/kudos': typeof DashboardAuthenticatedKudosRoute
  '/dashboard/_authenticated/mcp': typeof DashboardAuthenticatedMcpRoute
  '/dashboard/_authenticated/members': typeof DashboardAuthenticatedMembersRoute
  '/dashboard/_authenticated/reports': typeof DashboardAuthenticatedReportsRoute
  '/dashboard/_authenticated/settings': typeof DashboardAuthenticatedSettingsRoute
  '/dashboard/_authenticated/standups': typeof DashboardAuthenticatedStandupsRoute
  '/dashboard/_authenticated/today': typeof DashboardAuthenticatedTodayRoute
  '/dashboard/_authenticated/webhooks': typeof DashboardAuthenticatedWebhooksRoute
  '/dashboard/_authenticated/': typeof DashboardAuthenticatedIndexRoute
  '/dashboard/_authenticated/connect/$programId': typeof DashboardAuthenticatedConnectProgramIdRoute
  '/dashboard/_authenticated/connect/attendance': typeof DashboardAuthenticatedConnectAttendanceRoute
  '/dashboard/_authenticated/connect/new': typeof DashboardAuthenticatedConnectNewRoute
  '/dashboard/_authenticated/connect/': typeof DashboardAuthenticatedConnectIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/auth/result'
    | '/dashboard/login'
    | '/email/result'
    | '/feed/$token'
    | '/dashboard/connect'
    | '/connect/zoom/result'
    | '/dashboard/analytics'
    | '/dashboard/automation'
    | '/dashboard/insights'
    | '/dashboard/kudos'
    | '/dashboard/mcp'
    | '/dashboard/members'
    | '/dashboard/reports'
    | '/dashboard/settings'
    | '/dashboard/standups'
    | '/dashboard/today'
    | '/dashboard/webhooks'
    | '/dashboard/'
    | '/dashboard/connect/$programId'
    | '/dashboard/connect/attendance'
    | '/dashboard/connect/new'
    | '/dashboard/connect/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/auth/result'
    | '/dashboard/login'
    | '/email/result'
    | '/feed/$token'
    | '/connect/zoom/result'
    | '/dashboard/analytics'
    | '/dashboard/automation'
    | '/dashboard/insights'
    | '/dashboard/kudos'
    | '/dashboard/mcp'
    | '/dashboard/members'
    | '/dashboard/reports'
    | '/dashboard/settings'
    | '/dashboard/standups'
    | '/dashboard/today'
    | '/dashboard/webhooks'
    | '/dashboard/connect/$programId'
    | '/dashboard/connect/attendance'
    | '/dashboard/connect/new'
    | '/dashboard/connect'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/_authenticated'
    | '/auth/result'
    | '/dashboard/login'
    | '/email/result'
    | '/feed/$token'
    | '/dashboard/_authenticated/connect'
    | '/connect/zoom/result'
    | '/dashboard/_authenticated/analytics'
    | '/dashboard/_authenticated/automation'
    | '/dashboard/_authenticated/insights'
    | '/dashboard/_authenticated/kudos'
    | '/dashboard/_authenticated/mcp'
    | '/dashboard/_authenticated/members'
    | '/dashboard/_authenticated/reports'
    | '/dashboard/_authenticated/settings'
    | '/dashboard/_authenticated/standups'
    | '/dashboard/_authenticated/today'
    | '/dashboard/_authenticated/webhooks'
    | '/dashboard/_authenticated/'
    | '/dashboard/_authenticated/connect/$programId'
    | '/dashboard/_authenticated/connect/attendance'
    | '/dashboard/_authenticated/connect/new'
    | '/dashboard/_authenticated/connect/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  AuthResultRoute: typeof AuthResultRoute
  EmailResultRoute: typeof EmailResultRoute
  FeedTokenRoute: typeof FeedTokenRoute
  ConnectZoomResultRoute: typeof ConnectZoomResultRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/result': {
      id: '/auth/result'
      path: '/auth/result'
      fullPath: '/auth/result'
      preLoaderRoute: typeof AuthResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/_authenticated': {
      id: '/dashboard/_authenticated'
      path: ''
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardAuthenticatedRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/login': {
      id: '/dashboard/login'
      path: '/login'
      fullPath: '/dashboard/login'
      preLoaderRoute: typeof DashboardLoginRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/email/result': {
      id: '/email/result'
      path: '/email/result'
      fullPath: '/email/result'
      preLoaderRoute: typeof EmailResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed/$token': {
      id: '/feed/$token'
      path: '/feed/$token'
      fullPath: '/feed/$token'
      preLoaderRoute: typeof FeedTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect/zoom/result': {
      id: '/connect/zoom/result'
      path: '/connect/zoom/result'
      fullPath: '/connect/zoom/result'
      preLoaderRoute: typeof ConnectZoomResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/_authenticated/': {
      id: '/dashboard/_authenticated/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardAuthenticatedIndexRouteImport
      parentRoute: typeof DashboardAuthenticatedRouteRoute
    }
    '/dashboard/_authenticated/analytics': {
      id: '/dashboard/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAuthenticatedAnalyticsRouteImport
      parentRoute: typeof DashboardAuthenticatedRouteRoute
    }
    '/dashboard/_authenticated/automation': {
      id: '/dashboard/_authenticated/automation'
      path: '/automation'
      fullPath: '/dashboard/automation'
      preLoaderRoute: typeof DashboardAuthenticatedAutomationRouteImport
      parentRoute: typeof DashboardAuthenticatedRouteRoute
    }
    '/dashboard/_authenticated/connect': {
      id: '/dashboard/_authenticated/connect'
      path: '/connect'
      fullPath: '/dashboard/connect'
      preLoaderRoute: typeof DashboardAuthenticatedConnectRouteRouteImport
      parentRoute: typeof DashboardAuthenticatedRouteRoute
    }
    '/dashboard/_authenticated/insights': {
      id: '/dashboard/_authenticated/insights'
      path: '/insights'
      fullPath: '/dashboard/insights'
      preLoaderRoute: typeof DashboardAuthenticatedInsightsRouteImport
      parentRoute: typeof DashboardAuthenticatedRouteRoute
    }
    '/dashboard/_authenticated/kudos': {
      id: '/dashboard/_authenticated/kudos'
      path: '/kudos'
      fullPath: '/dashboard/kudos'
      preLoaderRoute: typeof DashboardAuthenticatedKudosRouteImport
      parentRoute: typeof DashboardAuthenticatedRouteRoute
    }
    '/dashboard/_authenticated/mcp': {
      id: '/dashboard/_authenticated/mcp'
      path: '/mcp'
      fullPath: '/dashboard/mcp'
      preLoaderRoute: typeof DashboardAuthenticatedMcpRouteImport
      parentRoute: typeof DashboardAuthenticatedRouteRoute
    }
    '/dashboard/_authenticated/members': {
      id: '/dashboard/_authenticated/members'
      path: '/members'
      fullPath: '/dashboard/members'
      preLoaderRoute: typeof DashboardAuthenticatedMembersRouteImport
      parentRoute: typeof DashboardAuthenticatedRouteRoute
    }
    '/dashboard/_authenticated/reports': {
      id: '/dashboard/_authenticated/reports'
      path: '/reports'
      fullPath: '/dashboard/reports'
      preLoaderRoute: typeof DashboardAuthenticatedReportsRouteImport
      parentRoute: typeof DashboardAuthenticatedRouteRoute
    }
    '/dashboard/_authenticated/settings': {
      id: '/dashboard/_authenticated/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardAuthenticatedSettingsRouteImport
      parentRoute: typeof DashboardAuthenticatedRouteRoute
    }
    '/dashboard/_authenticated/standups': {
      id: '/dashboard/_authenticated/standups'
      path: '/standups'
      fullPath: '/dashboard/standups'
      preLoaderRoute: typeof DashboardAuthenticatedStandupsRouteImport
      parentRoute: typeof DashboardAuthenticatedRouteRoute
    }
    '/dashboard/_authenticated/today': {
      id: '/dashboard/_authenticated/today'
      path: '/today'
      fullPath: '/dashboard/today'
      preLoaderRoute: typeof DashboardAuthenticatedTodayRouteImport
      parentRoute: typeof DashboardAuthenticatedRouteRoute
    }
    '/dashboard/_authenticated/webhooks': {
      id: '/dashboard/_authenticated/webhooks'
      path: '/webhooks'
      fullPath: '/dashboard/webhooks'
      preLoaderRoute: typeof DashboardAuthenticatedWebhooksRouteImport
      parentRoute: typeof DashboardAuthenticatedRouteRoute
    }
    '/dashboard/_authenticated/connect/': {
      id: '/dashboard/_authenticated/connect/'
      path: '/'
      fullPath: '/dashboard/connect/'
      preLoaderRoute: typeof DashboardAuthenticatedConnectIndexRouteImport
      parentRoute: typeof DashboardAuthenticatedConnectRouteRoute
    }
    '/dashboard/_authenticated/connect/$programId': {
      id: '/dashboard/_authenticated/connect/$programId'
      path: '/$programId'
      fullPath: '/dashboard/connect/$programId'
      preLoaderRoute: typeof DashboardAuthenticatedConnectProgramIdRouteImport
      parentRoute: typeof DashboardAuthenticatedConnectRouteRoute
    }
    '/dashboard/_authenticated/connect/attendance': {
      id: '/dashboard/_authenticated/connect/attendance'
      path: '/attendance'
      fullPath: '/dashboard/connect/attendance'
      preLoaderRoute: typeof DashboardAuthenticatedConnectAttendanceRouteImport
      parentRoute: typeof DashboardAuthenticatedConnectRouteRoute
    }
    '/dashboard/_authenticated/connect/new': {
      id: '/dashboard/_authenticated/connect/new'
      path: '/new'
      fullPath: '/dashboard/connect/new'
      preLoaderRoute: typeof DashboardAuthenticatedConnectNewRouteImport
      parentRoute: typeof DashboardAuthenticatedConnectRouteRoute
    }
  }
}

interface DashboardAuthenticatedConnectRouteRouteChildren {
  DashboardAuthenticatedConnectProgramIdRoute: typeof DashboardAuthenticatedConnectProgramIdRoute
  DashboardAuthenticatedConnectAttendanceRoute: typeof DashboardAuthenticatedConnectAttendanceRoute
  DashboardAuthenticatedConnectNewRoute: typeof DashboardAuthenticatedConnectNewRoute
  DashboardAuthenticatedConnectIndexRoute: typeof DashboardAuthenticatedConnectIndexRoute
}

const DashboardAuthenticatedConnectRouteRouteChildren: DashboardAuthenticatedConnectRouteRouteChildren =
  {
    DashboardAuthenticatedConnectProgramIdRoute:
      DashboardAuthenticatedConnectProgramIdRoute,
    DashboardAuthenticatedConnectAttendanceRoute:
      DashboardAuthenticatedConnectAttendanceRoute,
    DashboardAuthenticatedConnectNewRoute:
      DashboardAuthenticatedConnectNewRoute,
    DashboardAuthenticatedConnectIndexRoute:
      DashboardAuthenticatedConnectIndexRoute,
  }

const DashboardAuthenticatedConnectRouteRouteWithChildren =
  DashboardAuthenticatedConnectRouteRoute._addFileChildren(
    DashboardAuthenticatedConnectRouteRouteChildren,
  )

interface DashboardAuthenticatedRouteRouteChildren {
  DashboardAuthenticatedConnectRouteRoute: typeof DashboardAuthenticatedConnectRouteRouteWithChildren
  DashboardAuthenticatedAnalyticsRoute: typeof DashboardAuthenticatedAnalyticsRoute
  DashboardAuthenticatedAutomationRoute: typeof DashboardAuthenticatedAutomationRoute
  DashboardAuthenticatedInsightsRoute: typeof DashboardAuthenticatedInsightsRoute
  DashboardAuthenticatedKudosRoute: typeof DashboardAuthenticatedKudosRoute
  DashboardAuthenticatedMcpRoute: typeof DashboardAuthenticatedMcpRoute
  DashboardAuthenticatedMembersRoute: typeof DashboardAuthenticatedMembersRoute
  DashboardAuthenticatedReportsRoute: typeof DashboardAuthenticatedReportsRoute
  DashboardAuthenticatedSettingsRoute: typeof DashboardAuthenticatedSettingsRoute
  DashboardAuthenticatedStandupsRoute: typeof DashboardAuthenticatedStandupsRoute
  DashboardAuthenticatedTodayRoute: typeof DashboardAuthenticatedTodayRoute
  DashboardAuthenticatedWebhooksRoute: typeof DashboardAuthenticatedWebhooksRoute
  DashboardAuthenticatedIndexRoute: typeof DashboardAuthenticatedIndexRoute
}

const DashboardAuthenticatedRouteRouteChildren: DashboardAuthenticatedRouteRouteChildren =
  {
    DashboardAuthenticatedConnectRouteRoute:
      DashboardAuthenticatedConnectRouteRouteWithChildren,
    DashboardAuthenticatedAnalyticsRoute: DashboardAuthenticatedAnalyticsRoute,
    DashboardAuthenticatedAutomationRoute:
      DashboardAuthenticatedAutomationRoute,
    DashboardAuthenticatedInsightsRoute: DashboardAuthenticatedInsightsRoute,
    DashboardAuthenticatedKudosRoute: DashboardAuthenticatedKudosRoute,
    DashboardAuthenticatedMcpRoute: DashboardAuthenticatedMcpRoute,
    DashboardAuthenticatedMembersRoute: DashboardAuthenticatedMembersRoute,
    DashboardAuthenticatedReportsRoute: DashboardAuthenticatedReportsRoute,
    DashboardAuthenticatedSettingsRoute: DashboardAuthenticatedSettingsRoute,
    DashboardAuthenticatedStandupsRoute: DashboardAuthenticatedStandupsRoute,
    DashboardAuthenticatedTodayRoute: DashboardAuthenticatedTodayRoute,
    DashboardAuthenticatedWebhooksRoute: DashboardAuthenticatedWebhooksRoute,
    DashboardAuthenticatedIndexRoute: DashboardAuthenticatedIndexRoute,
  }

const DashboardAuthenticatedRouteRouteWithChildren =
  DashboardAuthenticatedRouteRoute._addFileChildren(
    DashboardAuthenticatedRouteRouteChildren,
  )

interface DashboardRouteRouteChildren {
  DashboardAuthenticatedRouteRoute: typeof DashboardAuthenticatedRouteRouteWithChildren
  DashboardLoginRoute: typeof DashboardLoginRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardAuthenticatedRouteRoute:
    DashboardAuthenticatedRouteRouteWithChildren,
  DashboardLoginRoute: DashboardLoginRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  AuthResultRoute: AuthResultRoute,
  EmailResultRoute: EmailResultRoute,
  FeedTokenRoute: FeedTokenRoute,
  ConnectZoomResultRoute: ConnectZoomResultRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
